spring:
  application:
    name: simple-ai
  profiles:
    active: @spring.active@

  # entity时间类型数据格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 数据库返回时间格式化
    time-zone: GMT+8 # 时区设置

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: false

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # mapper扫描路径
  configuration:
    auto-mapping-behavior: full # MyBatis 自动映射策略：none-不启用自动映射，partial-只对非嵌套的 resultMap 进行自动映射，full-对所有的 resultMap 都进行自动映射
    auto-mapping-unknown-column-behavior: none # MyBatis 自动映射时未知列或未知属性处理策略：none-不做任何处理 (默认值)，warning-日志打印出来，failing-当作映射失败处理，并抛出异常和详细信息
    cache-enabled: false # mybatis二级缓存
    call-setters-on-nulls: false # 指定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法，通常运用于有 Map.keySet() 依赖或 null 值初始化的情况。

    # Mybatis一级缓存，单服务架构中（有且仅有只有一个程序提供相同服务），一级缓存开启不会影响业务，只会提高性能。
    # 微服务架构中需要关闭一级缓存，原因：Service1先查询数据，若之后Service2修改了数据，之后Service1又再次以同样的查询条件查询数据，因走缓存会出现查处的数据不是最新数据
    # session-session级别缓存，同一个session相同查询语句不会再次查询数据库，statement-关闭一级缓存
    local-cache-scope: statement
    map-underscore-to-camel-case: true # 下划线自动驼峰转化，如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
  global-config:
    banner: false # 控制台MP logo是否显示
    db-config:
      logic-delete-field: deleted
      logic-delete-value: '''DELETE'''
      logic-not-delete-value: '''OK'''

