server:
  port: 8000
spring:
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://develop.dev.joyswon.com:5432/simple-${spring.application.name}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: postgres
    password: 123456
    hikari:
      auto-commit: true # 自动提交
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      idle-timeout: 30000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      maxLifeTime: 600000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      maximum-pool-size: 100 # 连接池中允许的最大连接数。缺省值：10
      minimum-idle: 10 # 最小连接数
  data:
    redis:
      database: 1
      host: develop.dev.joyswon.com
      port: 6379
      password: 12345678
      timeout: 3000 # 连接超时时间（毫秒），缺省值：3000
      lettuce.pool:
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 10 # 连接池中的最小空闲连接
        max-active: 100 # 连接池的最大数据库连接数。设为0表示无限制。一般设置为并发量
        max-wait: 3000 # 从连接池中获取连接的最大等待时间（毫秒）
  rabbitmq:
    addresses: develop.dev.joyswon.com:5672
    username: admin
    password: Abc$123456789
    listener:
      simple:
        acknowledge-mode: MANUAL # 确认模式：MANUAL-手动ack，AUTO-自动ack，失败需要手动抛出异常，NONE-没有ack
        prefetch: 1 # 未确认消息的最大数量，也叫作分发模式：0-轮训，每台服务器一次循环，1-公平分发，是服务器压力进行分发，> 1：预取数据的数量-适当增大可以提升消费速度
        default-requeue-rejected: false # 消费失败的q是否重新放回队列重新消费
        # concurrency: 1 # 消费线程数
        # max-concurrency: 10 # 消费线程最大数量
# doc文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

  group-configs:
    - group: '基础服务'
      paths-to-match: '/**'
      packages-to-scan:
        - com.simple.common.auth.client.controller
        - com.simple.${spring.application.name}.controller

# 项目配置
simple:
  annex:
    # 附件上传配置
    server-url: http://minio.dev.joyswon.com
    access-key: admin
    access-secret: rXd5BErpRk
  event:
    type: mq # 事件实现方式
    concurrency: 1 # 事件消费并发数
  auth:
    hs-key: sInFHs4zRGIfrVTWVDdGJuKZRc0DfVBF # JWT密钥
    project-code: simple-ai # 项目编码

